databases:
  - name: budget_app
    databaseName: budget_app_y6ye
    user: budget_app_y6ye_user

services:
  - type: web
    name: BudgetPro
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_y6ye
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false